//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusRoute
    {
        public int BusRouteID { get; set; }
        public string RouteNumber { get; set; }
        public string RouteName { get; set; }
        public Nullable<int> ResponsibleUnitID { get; set; }
        public string OperationType { get; set; }
        public string OperationTime { get; set; }
        public Nullable<int> Fare { get; set; }
        public Nullable<int> BusesAmount { get; set; }
        public string BusesTime { get; set; }
        public string BusesSpace { get; set; }
    }
}
